FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR app

EXPOSE 80   
EXPOSE 5024


#FILES
COPY ./Data/*.csproj ./Data/
RUN dotnet restore ./Data/Data.csproj
COPY ./NTTChallenge/*.csproj ./NTTChallenge/
RUN dotnet restore ./NTTChallenge/NTTChallenge.csproj



#SRC FILES
COPY ./NTTChallenge/ ./NTTChallenge/
COPY ./Data ./Data/
RUN dotnet publish ./NTTChallenge/NTTChallenge.csproj -c Release -o  appbuild 

#BUILD IMAGE
FROM mcr.microsoft.com/dotnet/sdk:5.0 
WORKDIR /app
COPY --from=build /app/appbuild .
ENTRYPOINT ["dotnet","NTTChallenge.dll"]

