version: '3.8'
services: 
    mysqlcontainerntt:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "TestPassword1234"
            MSSQL_PID: Express
        ports: 
            - "5043:1433"
    nttbankapi:
        image: nttchallengenetcore
        build: .
        depends_on: 
            - mysqlcontainerntt
        environment: 
            ServerName: "mysqlcontainerntt"
            Database: "NTTBanco"
            UserName: "SA"
            Password: "TestPassword1234"
        ports: 
            - "8003:5024"